<?php
namespace agilman\a2\model;


/**
 * Class BrowseProductCollectionModel
 *
 * A collection model for products when browsing. Separated from other product
 * collection models due to a different need in the products being collected.
 *
 * @package agilman/a2
 * @author  Andrew Gilman <a.gilman@massey.ac.nz>
 */
class BrowseProductCollectionModel extends Model
{
    /***
     * @var array $productIds, the IDs of all products to be generated by the collection model.
     */
    private $productIds;
    /***
     * @var int $N, the number of products collected by the model.
     */
    private $N;

    /**
     * @return int, the number of products collected by the model.
     */
    public function getN()
    {
        return $this->N;
    }

    /***
     * BrowseProductCollectionModel constructor.
     *
     * Collects a category of tools specified by the user.
     *
     * @param $tools string, the category of tools to be collected.
     * @param $stock bool, whether the user has requested to only display in stock items.
     *
     * @throws \mysqli_sql_exception, if the SQL query fails
     */
    public function __construct($tools, $stock)
    {
        parent::__construct();
        if ($stock == 'true') {
            if (!$result = $this->db->query("SELECT * FROM `product` LEFT JOIN `category` 
                                             ON `category`.`id` = `product`.`category`
                                             WHERE `category`.`name` = '$tools' 
                                             AND `product`.`stock_quantity` > 0;")) {
                throw new \mysqli_sql_exception($this->db->error, $this->db->errno);
            }
            $this->productIds = array_column($result->fetch_all(), 0);
            $this->N = $result->num_rows;
        } else {
            if (!$result = $this->db->query("SELECT * FROM `product` LEFT JOIN `category` 
                                             ON `category`.`id` = `product`.`category`
                                             WHERE `category`.`name` = '$tools';")) {
                throw new \mysqli_sql_exception($this->db->error, $this->db->errno);
            }
            $this->productIds = array_column($result->fetch_all(), 0);
            $this->N = $result->num_rows;
        }
    }

    /**
     * Get product collection
     * Get the products specified by the user
     * @return \Generator|ProductModel[] Products
     */
    public function getProducts()
    {
        foreach ($this->productIds as $id) {
            // Use a generator to save on memory/resources
            // load accounts from DB one at a time only when required
            yield (new ProductModel())->load($id);
        }
    }
}
