


<?php
session_start();
 include "header.phtml" 
 ?>
<!---------- Body starts --------------->
<script type = "text/javascript">
	 function showBrowse() {
	 	var stock = document.getElementById("stock").checked;
	 	var powerT = document.getElementById("powerT").checked;
	 	var spades = document.getElementById("spades").checked;
	 	var hammer = document.getElementById("hammer").checked;
	 	var paintB = document.getElementById("paintB").checked;

        

        xmlhttp=new XMLHttpRequest();


        xmlhttp.onreadystatechange=function() {
            if (this.readyState==4 && this.status==200) {
                document.getElementById("browse-result").innerHTML=this.responseText;

            }
        }

        xmlhttp.open("GET","browseQuery.php?stock="+stock+"&powerT="+powerT+"&spades="+spades+"&hammer="+hammer+"&paintB="+paintB,true);

        xmlhttp.send();
    }


</script>


<div id="wrapper">
	<!---------- Header Wrapper starts --------------->
	<div id="headerWrapper">
		<div id= "header" class="container">
			<div id= "logo">
				<h1><a href="<?= $linkTo('welcome'); ?>">ToolStocker</a></h1>
				</div>
			
		</div>

		<!--- Menu starts here -->
		<div id="menuBar" class="container">
				<ul>
					<li><a href="<?= $linkTo('welcome'); ?>">Home Page</a></li>
					<li><a href="<?= $linkTo('search'); ?>">Search</a></li>
					<li class="current_page"><a href= "<?= $linkTo('browse'); ?>">Browse</a></li>
					<li><a href="<?= $linkTo('logout'); ?>">Logout</a></li>
				</ul>

			</div>
	</div>
	<!---------- Header Wrapper & Menu End here --------------->

	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content" class="container">
			<div class = "title">
			<h2>Browse Menu</h2>
			</div>
			<div id = "browse-panel">

			<fieldset>
  				  <legend>Choose Browse Filter Options</legend>

    			<div class= "filter-option">
					<input type='checkbox' id="stock" name='stock' value="stock" onchange="showBrowse()">
					<label for="stock">In-Stock Only</label>
				</div>
				<div class= "filter-option">
					<input type='checkbox' id="spades" name='spades' value="spades" onchange="showBrowse()">
					<label for="spades">Spades</label>
				</div>
				<div class= "filter-option">
					<input type='checkbox' id="hammer" name='hammer' value="hammer" onchange="showBrowse()">
					<label for="hammer">Hammer</label>
				</div>
				<div class= "filter-option">  
					<input type='checkbox' id="powerT" name='powerT' value="powerT" onchange="showBrowse()">
					<label for="powerT">Power Tools</label>
				</div>
				<div class= "filter-option">
					<input type='checkbox' id="paintB" name='paintB' value="paintB" onchange="showBrowse()">
					<label for="paintB">Paint Brushes</label>
				</div>

			</fieldset>
				
			</div>

			<div id = browse-result>


			</div> 
			<br>

			<br>
			
		</div>
	</div>
	<!--- Content Ends here ----------->
</div>



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>

