




<?php include "header.phtml" ?>
<!---------- Body starts --------------->

<div id="wrapper">
	<!---------- Header Wrapper starts --------------->
	<div id="headerWrapper">
		<div id= "header" class="container">
			<div id= "logo">
				<h1><a href="<?= $linkTo('home'); ?>">ToolStocker<a></h1>
				</div>
			
		</div>
		
	</div>

	<!---------- Header Wrapper End here --------------->

	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content">
			<div class = "title">
			<h2>Registration Form</h2>
			</div>
		   <div id="registration">
        <form action="<?= $linkTo('accountCreate'); ?>" method="post">
            <p>Name: <input type="text" placeholder="Name" required></p>
            <p>Username: <input type="text" placeholder="Username" required></p>
            <p>Email: <input type="text" placeholder="Email" required></p>
            <p>Password: <input type="password" placeholder="Password" required></p>
            <p>Confirm Password: <input type="password" placeholder="Password" required></p>
            </div>
            <input type="submit" value="Register" >
        </form>
		    <br> 	
			
		</div>
	</div>
	<!--- Content Ends here ----------->
</div>







<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>
