<?php include "header.phtml" ?>




<div id=wrapper>
	<div id=headerWrapper>
		<div id=menuBar>
			<div id= logo>
			</div>
		</div>
	</div>
	<div id= content>
		<h1>Welcome to ToolStocker</h1>
		<div id = page>
			
		
    <h2>Registration Form</h2>
        <form action="" method="post">
            <p>Name: <input type="text" placeholder="Name" required></p>
            <p>Username: <input type="text" placeholder="Username" required></p>
            <p>Email: <input type="text" placeholder="Email" required></p>
            <p>Password: <input type="text" placeholder="Password" required></p>
            <p>Confirm Password: <input type="text" placeholder="Password" required></p>
            <input type="submit" value="Register">
        </form>
		</div>
	</div>
</div>





<?php include "footer.phtml" ?>
