<?php 
session_start();
include "header.phtml"
 ?>
 <!---------- Body starts-------------------->
<script type = "text/javascript">

    function showResult(str) {

        if (str.length==0) {
            document.getElementById("livesearch").innerHTML="";
            document.getElementById("livesearch").style.border="0px";
            return;
        }

        xmlhttp=new XMLHttpRequest();


        xmlhttp.onreadystatechange=function() {
            if (this.readyState==4 && this.status==200) {
                document.getElementById("livesearch").innerHTML=this.responseText;

            }
        }

        xmlhttp.open("GET","livesearch.php?q="+str,true);

        xmlhttp.send();
    }
</script>

<div id="wrapper">
	<!---------- Header Wrapper starts --------------->
	<div id="headerWrapper">
		<div id= "header" class="container">
			<div id= "logo">
				<h1><a href="<?= $linkTo('welcome'); ?>">ToolStocker</a></h1>
				</div>
			
		</div>

		<!--- Menu starts here -->
		<div id="menuBar" class="container">
				<ul>
					<li><a href="<?= $linkTo('welcome'); ?>">Home Page</a></li>
					<li class="current_page"><a href="<?= $linkTo('search'); ?>">Search</a></li>
					<li><a href= "<?= $linkTo('browse'); ?>">Browse</a></li>
					<li><a href="<?= $linkTo('logout'); ?>">Logout</a></li>
				</ul>

			</div>
	</div>
	<!---------- Header Wrapper & Menu End here --------------->

	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content" class="container">
			<div class = "title">
			<h2>Search Menu</h2>
			</div>
            <form>
			<p> Search <input type="text" size="60" onkeyup="showResult(this.value)"></p>
			<br>
                <p><b>Search Results</b></p>
                <div id="livesearch" > </div>

            </form>
			<br>
		</div>
	</div>
	<!--- Content Ends here ----------->
</div>



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>

