<?php 
session_start();
include "header.phtml"
 ?>
 <script type = "text/javascript" src="src/js/livesearch.js"></script>
 <!---------- Body starts-------------------->




		<!--- Menu starts here -->
		<div id="menuBar" class="container">
				<ul>
					<li><a href="<?= $linkTo('welcome'); ?>">Home Page</a></li>
					<li class="current_page"><a href="<?= $linkTo('search'); ?>">Search</a></li>
					<li><a href= "<?= $linkTo('browse'); ?>">Browse</a></li>
					<li><a href="<?= $linkTo('logout'); ?>">Logout</a></li>
				</ul>

			</div>
	</div>
	<!---------- Header Wrapper & Menu End here --------------->

	<!--- Content Start -->
	<div id= "page">
		
		<div id = "content" class="container">
			<div class = "title">
			<h2>Search Menu</h2>
			</div>
            <form>
            	<div id="search-bar">
					<p> Search:  <input type="text" size="50" onkeyup="showResult(this.value)"></p>
				</div>
				<br>
				<div id = "search">
                	<p><b>Search Results</b></p>
                	<div id="livesearch" > </div>
                </div>
              
            </form>
			<br>
		</div>
	</div>
	<!--- Content Ends here ----------->
</div>



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>

