

<?php 

session_start();
include "header.phtml"
 ?>
<!---------- Body starts --------------->

<div id="wrapper">
	<div id="headerWrapper">
		<div id= "header" class="container">
			<div id= "logo">
				<h1><a href="<?= $linkTo('welcome'); ?>">ToolStocker</a></h1>
				</div>
			
		</div>
		<div id="menuBar" class="container">
				<ul>
					<li><a href="<?= $linkTo('welcome'); ?>">Home Page</a></li>
					<li class="current_page"><a href="<?= $linkTo('search'); ?>">Search</a></li>
					<li><a href= "<?= $linkTo('browse'); ?>">Browse</a></li>
					<li><a href="#">Logout</a></li>
				</ul>

			</div>
	</div>
	<div id= "page">
		
		<div id = "content">
			<div class = "title">
			<h2>Search Menu</h2>
			</div>
			<p> Search <input type="search" name="search" id="search" size="60" placeholder="e.g. Hammer"></p>
			<br>
			<br>
			<p><b>Search Results</b></p>
			<div id ="result">
				<script>
					$(document).ready(function(){})
				</script>
			</div>
			
		</div>
	</div>
</div>



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>

