




<?php 

include "header.phtml" ?>
<!---------- Body starts --------------->

<div id="wrapper">
	<!---------- Header Wrapper starts --------------->
	<div id="headerWrapper">
		<div id= "header" class="container">
			<div id= "logo">
				<h1><a href="<?= $linkTo('welcome'); ?>">ToolStocker</a></h1>
				</div>
			
		</div>

		<!--- Menu starts here -->
		<div id="menuBar" class="container">
				<ul>
					<li class="current_page"><a href="<?= $linkTo('welcome'); ?>">Home Page</a></li>
					<li><a href="<?= $linkTo('search'); ?>">Search</a></li>
					<li><a href= "<?= $linkTo('browse'); ?>">Browse</a></li>
					<li><a href="<?= $linkTo('logout'); ?>">Logout</a></li>
				</ul>

			</div>
	</div>
<!---------- Header Wrapper & Menu End here --------------->

<!--- Content Start -->
	<div id= "page">
		
		<div id = "content" class="containers">
			<div class = "title">
			<h2>Welcome to ToolStocker</h2>
			</div>
			<div class="partition">
				<p>To do things please click on browse or search a find what you want to find....</p>
			</div>
			<br>
			<br>
			
		</div>
	</div>
	<!--- Content Ends here ----------->
</div>



<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>

